import bcrypt from "bcryptjs";
import { eq, sql } from "drizzle-orm";
import { v4 as uuidv4 } from "uuid";

import { db } from "./index";
import {
    agentExecutions,
    agentRecommendations,
    approvalPolicies,
    auditLogs,
    comments,
    complianceObligations,
    contacts,
    contracts,
    demandForecasts,
    documents,
    fraudAlerts,
    goodsReceipts,
    importJobs,
    invoices,
    marketPriceIndex,
    matchingTolerances,
    notifications,
    orderItems,
    parts,
    paymentOptimizations,
    procurementOrders,
    qcInspections,
    requisitions,
    rfqItems,
    rfqSuppliers,
    rfqs,
    savingsRecords,
    sourcingEvents,
    sourcingMessages,
    supplierActionPlans,
    supplierPerformanceLogs,
    supplierRequests,
    suppliers,
    supportTickets,
    systemTelemetry,
    users,
    workflowTasks,
} from "./schema";

export const RESET_TABLES = [
    "webhook_deliveries",
    "webhooks",
    "support_tickets",
    "comments",
    "notifications",
    "chat_history",
    "audit_logs",
    "system_telemetry",
    "agent_recommendations",
    "agent_executions",
    "fraud_alerts",
    "payment_optimizations",
    "demand_forecasts",
    "market_price_index",
    "savings_records",
    "workflow_tasks",
    "supplier_requests",
    "supplier_action_plans",
    "compliance_obligations",
    "sourcing_messages",
    "sourcing_events",
    "rfq_suppliers",
    "rfq_items",
    "documents",
    "qc_inspections",
    "goods_receipts",
    "invoices",
    "order_items",
    "procurement_orders",
    "requisitions",
    "contracts",
    "rfqs",
    "contacts",
    "matching_tolerances",
    "approval_policies",
    "import_jobs",
    "supplier_performance_logs",
    "parts",
    "cost_centers",
    "budgets",
    "suppliers",
    "users",
] as const;

export type PreservedAdminUser = {
    id: string;
    name: string;
    email: string;
    employeeId: string | null;
    phoneNumber: string | null;
    twoFactorSecret: string | null;
    isTwoFactorEnabled: boolean | null;
    password: string;
    role: "admin" | "user" | "supplier" | null;
    department: string | null;
    createdAt: Date | null;
};

export type DemoWorkspaceResult = {
    counts: Record<string, number>;
};

const DAY = 24 * 60 * 60 * 1000;

function decimal(value: number) {
    return value.toFixed(2);
}

function dateFromNow(daysOffset: number, hour = 10, minute = 0) {
    const date = new Date(Date.now() + (daysOffset * DAY));
    date.setHours(hour, minute, 0, 0);
    return date;
}

function safeDate(value: Date | null | undefined) {
    return value ?? new Date();
}

async function getExistingWorkspaceTables(executor: typeof db) {
    const existingTablesResult = await executor.execute(
        sql.raw("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
    );

    return new Set(
        existingTablesResult.rows
            .map((row: { tablename?: unknown }) => row.tablename)
            .filter((value: unknown): value is string => typeof value === "string")
    );
}

async function truncateWorkspaceTables(executor: typeof db) {
    const existingTables = await getExistingWorkspaceTables(executor);
    const tablesToReset = RESET_TABLES.filter((tableName) => existingTables.has(tableName));

    if (tablesToReset.length === 0) {
        return;
    }

    await executor.execute(
        sql.raw(
            `TRUNCATE TABLE ${tablesToReset.map((tableName) => `"${tableName}"`).join(", ")} RESTART IDENTITY CASCADE`
        )
    );
}

async function restoreAdmins(executor: typeof db, preservedAdmins: PreservedAdminUser[]) {
    await executor.insert(users).values(
        preservedAdmins.map((admin) => ({
            id: admin.id,
            name: admin.name,
            email: admin.email,
            employeeId: admin.employeeId,
            phoneNumber: admin.phoneNumber,
            twoFactorSecret: admin.twoFactorSecret,
            isTwoFactorEnabled: admin.isTwoFactorEnabled ?? false,
            password: admin.password,
            role: admin.role ?? "admin",
            department: admin.department,
            supplierId: null,
            createdAt: safeDate(admin.createdAt),
        }))
    );
}

export async function clearWorkspacePreservingAdmins(preservedAdmins: PreservedAdminUser[]) {
    if (preservedAdmins.length === 0) {
        throw new Error("Reset blocked because no admin account could be preserved.");
    }

    await db.transaction(async (tx) => {
        await truncateWorkspaceTables(tx as unknown as typeof db);
        await restoreAdmins(tx as unknown as typeof db, preservedAdmins);
    });
}

export async function seedDemoWorkspace(preservedAdmins: PreservedAdminUser[]): Promise<DemoWorkspaceResult> {
    if (preservedAdmins.length === 0) {
        throw new Error("Demo seed blocked because no admin account could be preserved.");
    }

    return db.transaction(async (tx) => {
        const executor = tx as unknown as typeof db;
        await truncateWorkspaceTables(executor);
        await restoreAdmins(executor, preservedAdmins);

        const primaryAdmin = preservedAdmins[0];
        const sharedPassword = await bcrypt.hash("password", 10);

        const internalUsers = {
            operations: uuidv4(),
            finance: uuidv4(),
            sourcing: uuidv4(),
            supplierPortal: uuidv4(),
        };

        const supplierIds = {
            atlas: uuidv4(),
            nordforge: uuidv4(),
            pacific: uuidv4(),
            redMesa: uuidv4(),
            desert: uuidv4(),
        };

        const partIds = {
            microcontroller: uuidv4(),
            steelBracket: uuidv4(),
            servoMotor: uuidv4(),
            lithiumPack: uuidv4(),
            logisticsLane: uuidv4(),
            resinPellets: uuidv4(),
            copperHarness: uuidv4(),
            warehouseSensors: uuidv4(),
        };

        const requisitionIds = {
            evProgram: uuidv4(),
            warehouseUpgrade: uuidv4(),
            logisticsBuffer: uuidv4(),
        };

        const contractIds = {
            atlasFramework: uuidv4(),
            nordforgeSteel: uuidv4(),
            pacificElectronics: uuidv4(),
            redMesaCarrier: uuidv4(),
        };

        const rfqIds = {
            batteryPack: uuidv4(),
            logisticsReroute: uuidv4(),
        };

        const orderIds = {
            atlasMarch: uuidv4(),
            nordforgeApril: uuidv4(),
            pacificMay: uuidv4(),
            desertJune: uuidv4(),
            redMesaJuly: uuidv4(),
        };

        const invoiceIds = {
            atlasPaid: uuidv4(),
            nordforgeMatched: uuidv4(),
            pacificPending: uuidv4(),
            redMesaDisputed: uuidv4(),
        };

        const receiptIds = {
            atlas: uuidv4(),
            nordforge: uuidv4(),
            desert: uuidv4(),
        };

        const complianceIds = {
            atlasIso: uuidv4(),
            nordforgeCyber: uuidv4(),
            redMesaEsg: uuidv4(),
        };

        await executor.insert(users).values([
            {
                id: internalUsers.operations,
                name: "Priya Sharma",
                email: "priya.sharma@axiom.demo",
                employeeId: "AX-OPS-102",
                phoneNumber: "+91-90000-10001",
                password: sharedPassword,
                role: "user",
                department: "Operations",
                createdAt: dateFromNow(-300, 9),
            },
            {
                id: internalUsers.finance,
                name: "Nikhil Mehta",
                email: "nikhil.mehta@axiom.demo",
                employeeId: "AX-FIN-211",
                phoneNumber: "+91-90000-10002",
                password: sharedPassword,
                role: "user",
                department: "Finance",
                createdAt: dateFromNow(-280, 9),
            },
            {
                id: internalUsers.sourcing,
                name: "Sara Iyer",
                email: "sara.iyer@axiom.demo",
                employeeId: "AX-SRC-118",
                phoneNumber: "+91-90000-10003",
                password: sharedPassword,
                role: "user",
                department: "Strategic Sourcing",
                createdAt: dateFromNow(-260, 9),
            },
        ]);

        await executor.insert(suppliers).values([
            {
                id: supplierIds.atlas,
                name: "Atlas Components India",
                contactEmail: "sales@atlas-components.demo",
                status: "active",
                lifecycleStatus: "active",
                riskScore: 34,
                performanceScore: 92,
                esgScore: 78,
                financialScore: 85,
                onTimeDeliveryRate: decimal(97.3),
                defectRate: decimal(0.8),
                collaborationScore: 89,
                responsivenessScore: 91,
                categories: ["Electronics", "Controls"],
                abcClassification: "A",
                carbonFootprintScope1: decimal(86.0),
                carbonFootprintScope2: decimal(42.0),
                carbonFootprintScope3: decimal(158.0),
                conflictMineralsStatus: "compliant",
                lastAuditDate: dateFromNow(-45),
                lastRiskAudit: dateFromNow(-20),
                isoCertifications: ["ISO 9001", "ISO 14001", "ISO 27001"],
                esgEnvironmentScore: 75,
                esgSocialScore: 80,
                esgGovernanceScore: 79,
                financialHealthRating: "A",
                tierLevel: "tier_1",
                isConflictMineralCompliant: "yes",
                modernSlaveryStatement: "yes",
                latitude: "12.9715987",
                longitude: "77.5945627",
                countryCode: "IN",
                city: "Bengaluru",
                segment: "strategic",
                createdAt: dateFromNow(-240),
            },
            {
                id: supplierIds.nordforge,
                name: "NordForge Precision GmbH",
                contactEmail: "account-team@nordforge.demo",
                status: "active",
                lifecycleStatus: "active",
                riskScore: 27,
                performanceScore: 88,
                esgScore: 82,
                financialScore: 89,
                onTimeDeliveryRate: decimal(95.6),
                defectRate: decimal(1.2),
                collaborationScore: 84,
                responsivenessScore: 87,
                categories: ["Steel", "Fabrication"],
                abcClassification: "A",
                carbonFootprintScope1: decimal(110.0),
                carbonFootprintScope2: decimal(58.0),
                carbonFootprintScope3: decimal(210.0),
                conflictMineralsStatus: "compliant",
                lastAuditDate: dateFromNow(-70),
                lastRiskAudit: dateFromNow(-25),
                isoCertifications: ["ISO 9001", "ISO 45001"],
                esgEnvironmentScore: 84,
                esgSocialScore: 79,
                esgGovernanceScore: 83,
                financialHealthRating: "AA-",
                tierLevel: "tier_1",
                isConflictMineralCompliant: "yes",
                modernSlaveryStatement: "yes",
                latitude: "48.7758459",
                longitude: "9.1829321",
                countryCode: "DE",
                city: "Stuttgart",
                segment: "leverage",
                createdAt: dateFromNow(-220),
            },
            {
                id: supplierIds.pacific,
                name: "Pacific Circuits Pte Ltd",
                contactEmail: "commercial@pacific-circuits.demo",
                status: "active",
                lifecycleStatus: "active",
                riskScore: 43,
                performanceScore: 81,
                esgScore: 74,
                financialScore: 78,
                onTimeDeliveryRate: decimal(93.8),
                defectRate: decimal(1.6),
                collaborationScore: 80,
                responsivenessScore: 82,
                categories: ["Batteries", "Electronics"],
                abcClassification: "B",
                carbonFootprintScope1: decimal(97.0),
                carbonFootprintScope2: decimal(61.0),
                carbonFootprintScope3: decimal(172.0),
                conflictMineralsStatus: "unknown",
                lastAuditDate: dateFromNow(-90),
                lastRiskAudit: dateFromNow(-32),
                isoCertifications: ["ISO 9001"],
                esgEnvironmentScore: 71,
                esgSocialScore: 73,
                esgGovernanceScore: 78,
                financialHealthRating: "A-",
                tierLevel: "tier_2",
                isConflictMineralCompliant: "yes",
                modernSlaveryStatement: "yes",
                latitude: "1.3520830",
                longitude: "103.8198390",
                countryCode: "SG",
                city: "Singapore",
                segment: "routine",
                createdAt: dateFromNow(-210),
            },
            {
                id: supplierIds.redMesa,
                name: "Red Mesa Logistics LLC",
                contactEmail: "ops@redmesa-logistics.demo",
                status: "active",
                lifecycleStatus: "suspended",
                riskScore: 78,
                performanceScore: 58,
                esgScore: 34,
                financialScore: 41,
                onTimeDeliveryRate: decimal(81.4),
                defectRate: decimal(4.3),
                collaborationScore: 54,
                responsivenessScore: 49,
                categories: ["Logistics", "Warehousing"],
                abcClassification: "C",
                carbonFootprintScope1: decimal(145.0),
                carbonFootprintScope2: decimal(74.0),
                carbonFootprintScope3: decimal(295.0),
                conflictMineralsStatus: "unknown",
                lastAuditDate: dateFromNow(-120),
                lastRiskAudit: dateFromNow(-8),
                isoCertifications: [],
                esgEnvironmentScore: 29,
                esgSocialScore: 38,
                esgGovernanceScore: 35,
                financialHealthRating: "B-",
                tierLevel: "critical",
                isConflictMineralCompliant: "no",
                modernSlaveryStatement: "no",
                latitude: "30.2671530",
                longitude: "-97.7430570",
                countryCode: "US",
                city: "Austin",
                segment: "high_risk",
                createdAt: dateFromNow(-45),
            },
            {
                id: supplierIds.desert,
                name: "Desert Petrochem Trading",
                contactEmail: "trading@desert-petrochem.demo",
                status: "active",
                lifecycleStatus: "active",
                riskScore: 52,
                performanceScore: 76,
                esgScore: 66,
                financialScore: 74,
                onTimeDeliveryRate: decimal(92.1),
                defectRate: decimal(1.9),
                collaborationScore: 77,
                responsivenessScore: 75,
                categories: ["Chemicals", "Resins"],
                abcClassification: "B",
                carbonFootprintScope1: decimal(126.0),
                carbonFootprintScope2: decimal(69.0),
                carbonFootprintScope3: decimal(221.0),
                conflictMineralsStatus: "compliant",
                lastAuditDate: dateFromNow(-95),
                lastRiskAudit: dateFromNow(-28),
                isoCertifications: ["ISO 9001", "Responsible Care"],
                esgEnvironmentScore: 63,
                esgSocialScore: 67,
                esgGovernanceScore: 69,
                financialHealthRating: "BBB+",
                tierLevel: "tier_2",
                isConflictMineralCompliant: "yes",
                modernSlaveryStatement: "yes",
                latitude: "24.4538840",
                longitude: "54.3773438",
                countryCode: "AE",
                city: "Abu Dhabi",
                segment: "bottleneck",
                createdAt: dateFromNow(-170),
            },
        ]);

        await executor.insert(users).values({
            id: internalUsers.supplierPortal,
            name: "Marta Singh",
            email: "marta.singh@atlas-components.demo",
            employeeId: "SUP-ATLAS-01",
            phoneNumber: "+91-90000-10004",
            password: sharedPassword,
            role: "supplier",
            department: "Supplier Portal",
            supplierId: supplierIds.atlas,
            createdAt: dateFromNow(-200, 8),
        });

        await executor.insert(parts).values([
            {
                id: partIds.microcontroller,
                sku: "EV-MCU-4800",
                name: "Vehicle Control MCU",
                description: "32-bit controller for drivetrain management",
                category: "Electronics",
                abcClassification: "A",
                price: decimal(8450),
                marketTrend: "up",
                stockLevel: 146,
                reorderPoint: 120,
                minStockLevel: 60,
                createdAt: dateFromNow(-250),
            },
            {
                id: partIds.steelBracket,
                sku: "CHS-BRK-201",
                name: "Chassis Support Bracket",
                description: "Laser-cut steel bracket for battery cage",
                category: "Steel",
                abcClassification: "A",
                price: decimal(1850),
                marketTrend: "stable",
                stockLevel: 420,
                reorderPoint: 300,
                minStockLevel: 160,
                createdAt: dateFromNow(-245),
            },
            {
                id: partIds.servoMotor,
                sku: "ROB-SRV-17",
                name: "Warehouse Servo Motor",
                description: "Servo motor for smart rack actuator",
                category: "Automation",
                abcClassification: "B",
                price: decimal(12400),
                marketTrend: "stable",
                stockLevel: 78,
                reorderPoint: 90,
                minStockLevel: 40,
                createdAt: dateFromNow(-240),
            },
            {
                id: partIds.lithiumPack,
                sku: "BAT-LFP-72",
                name: "LFP Battery Pack",
                description: "High-density pack for pilot fleet",
                category: "Batteries",
                abcClassification: "A",
                price: decimal(35800),
                marketTrend: "volatile",
                stockLevel: 32,
                reorderPoint: 26,
                minStockLevel: 14,
                createdAt: dateFromNow(-230),
            },
            {
                id: partIds.logisticsLane,
                sku: "LOG-LANE-01",
                name: "Dedicated Export Lane",
                description: "Quarterly logistics lane capacity",
                category: "Logistics",
                abcClassification: "B",
                price: decimal(95000),
                marketTrend: "up",
                stockLevel: 0,
                reorderPoint: 0,
                minStockLevel: 0,
                createdAt: dateFromNow(-225),
            },
            {
                id: partIds.resinPellets,
                sku: "RES-PBT-55",
                name: "PBT Resin Pellets",
                description: "Injection molding resin for connector housings",
                category: "Chemicals",
                abcClassification: "B",
                price: decimal(6900),
                marketTrend: "up",
                stockLevel: 95,
                reorderPoint: 80,
                minStockLevel: 30,
                createdAt: dateFromNow(-210),
            },
            {
                id: partIds.copperHarness,
                sku: "CAB-HRN-92",
                name: "Copper Harness Assembly",
                description: "Pre-terminated harness assembly",
                category: "Electronics",
                abcClassification: "A",
                price: decimal(5400),
                marketTrend: "stable",
                stockLevel: 188,
                reorderPoint: 140,
                minStockLevel: 70,
                createdAt: dateFromNow(-205),
            },
            {
                id: partIds.warehouseSensors,
                sku: "SEN-IOT-09",
                name: "Rack Health Sensor",
                description: "Temperature and humidity sensor for smart warehouse",
                category: "Automation",
                abcClassification: "B",
                price: decimal(3900),
                marketTrend: "down",
                stockLevel: 212,
                reorderPoint: 100,
                minStockLevel: 50,
                createdAt: dateFromNow(-200),
            },
        ]);

        await executor.insert(contacts).values([
            {
                id: uuidv4(),
                name: "Arjun Rao",
                email: "arjun.rao@atlas-components.demo",
                phone: "+91-98888-10010",
                company: "Atlas Components India",
                jobTitle: "Account Director",
                region: "South Asia",
                country: "India",
                continent: "Asia",
                currency: "INR",
                status: "active",
                notes: "Primary contact for electronics framework.",
                supplierId: supplierIds.atlas,
                createdBy: primaryAdmin.id,
                createdAt: dateFromNow(-190),
            },
            {
                id: uuidv4(),
                name: "Klara Weiss",
                email: "klara.weiss@nordforge.demo",
                phone: "+49-711-555-0199",
                company: "NordForge Precision GmbH",
                jobTitle: "Commercial Lead",
                region: "Europe",
                country: "Germany",
                continent: "Europe",
                currency: "EUR",
                status: "active",
                notes: "Handles annual steel price locks.",
                supplierId: supplierIds.nordforge,
                createdBy: internalUsers.sourcing,
                createdAt: dateFromNow(-175),
            },
            {
                id: uuidv4(),
                name: "Jordan Price",
                email: "jordan.price@redmesa-logistics.demo",
                phone: "+1-737-555-0143",
                company: "Red Mesa Logistics LLC",
                jobTitle: "Regional Operations Manager",
                region: "North America",
                country: "United States",
                continent: "North America",
                currency: "USD",
                status: "on_hold",
                notes: "Account is under remediation review.",
                supplierId: supplierIds.redMesa,
                createdBy: primaryAdmin.id,
                createdAt: dateFromNow(-35),
            },
        ]);

        await executor.insert(requisitions).values([
            {
                id: requisitionIds.evProgram,
                title: "EV Pilot Electronics Refresh",
                description: "Secure MCU and copper harness volume for the pilot vehicle program.",
                requestedById: internalUsers.sourcing,
                status: "approved",
                estimatedAmount: decimal(1650000),
                department: "Advanced Programs",
                createdAt: dateFromNow(-150),
            },
            {
                id: requisitionIds.warehouseUpgrade,
                title: "Smart Warehouse Sensor Upgrade",
                description: "Deploy health sensors and servo motors across the Pune warehouse.",
                requestedById: internalUsers.operations,
                status: "pending_approval",
                estimatedAmount: decimal(615000),
                department: "Operations",
                createdAt: dateFromNow(-45),
            },
            {
                id: requisitionIds.logisticsBuffer,
                title: "North America Logistics Buffer Capacity",
                description: "Reserve transport capacity before monsoon export surge.",
                requestedById: internalUsers.finance,
                status: "approved",
                estimatedAmount: decimal(950000),
                department: "Supply Chain",
                createdAt: dateFromNow(-20),
            },
        ]);

        await executor.insert(contracts).values([
            {
                id: contractIds.atlasFramework,
                supplierId: supplierIds.atlas,
                title: "Atlas Electronics Framework 2026",
                type: "framework_agreement",
                status: "active",
                value: decimal(3600000),
                validFrom: dateFromNow(-120),
                validTo: dateFromNow(220),
                noticePeriod: 45,
                renewalStatus: "manual",
                incoterms: "DAP",
                slaKpis: JSON.stringify({ otif: 97, defectRate: 1.2 }),
                liabilityCap: decimal(1800000),
                priceLockExpiry: dateFromNow(150),
                autoRenewalAlert: "true",
                createdAt: dateFromNow(-120),
            },
            {
                id: contractIds.nordforgeSteel,
                supplierId: supplierIds.nordforge,
                title: "NordForge Steel Program Lock",
                type: "service_agreement",
                status: "active",
                value: decimal(2100000),
                validFrom: dateFromNow(-180),
                validTo: dateFromNow(95),
                noticePeriod: 30,
                renewalStatus: "manual",
                incoterms: "FCA",
                slaKpis: JSON.stringify({ leadTimeDays: 21, scrapTarget: 0.8 }),
                liabilityCap: decimal(900000),
                priceLockExpiry: dateFromNow(60),
                autoRenewalAlert: "true",
                createdAt: dateFromNow(-180),
            },
            {
                id: contractIds.pacificElectronics,
                supplierId: supplierIds.pacific,
                title: "Pacific Battery Pack Pilot Contract",
                type: "one_off",
                status: "pending_renewal",
                value: decimal(1450000),
                validFrom: dateFromNow(-90),
                validTo: dateFromNow(18),
                noticePeriod: 21,
                renewalStatus: "manual",
                incoterms: "CIP",
                slaKpis: JSON.stringify({ warrantyMonths: 24, fieldFailureRate: 0.6 }),
                liabilityCap: decimal(620000),
                priceLockExpiry: dateFromNow(12),
                autoRenewalAlert: "true",
                createdAt: dateFromNow(-90),
            },
            {
                id: contractIds.redMesaCarrier,
                supplierId: supplierIds.redMesa,
                title: "Red Mesa Carrier Capacity Addendum",
                type: "service_agreement",
                status: "active",
                value: decimal(980000),
                validFrom: dateFromNow(-32),
                validTo: dateFromNow(58),
                noticePeriod: 15,
                renewalStatus: "manual",
                incoterms: "FCA",
                slaKpis: JSON.stringify({ dockToDockDays: 6, temperatureExcursions: 0 }),
                liabilityCap: decimal(350000),
                autoRenewalAlert: "true",
                createdAt: dateFromNow(-32),
            },
        ]);

        await executor.insert(rfqs).values([
            {
                id: rfqIds.batteryPack,
                title: "Battery Pack Phase-2 RFQ",
                description: "Request for 48 LFP packs with thermal telemetry support.",
                status: "open",
                deadline: dateFromNow(6, 17),
                category: "Batteries",
                createdById: primaryAdmin.id,
                createdAt: dateFromNow(-9),
            },
            {
                id: rfqIds.logisticsReroute,
                title: "Emergency Europe Reroute Capacity",
                description: "Spot-bid for bonded storage and alternate trucking capacity.",
                status: "closed",
                deadline: dateFromNow(-14, 17),
                category: "Logistics",
                createdById: internalUsers.operations,
                createdAt: dateFromNow(-24),
            },
        ]);

        await executor.insert(rfqItems).values([
            {
                id: uuidv4(),
                rfqId: rfqIds.batteryPack,
                partId: partIds.lithiumPack,
                quantity: 48,
            },
            {
                id: uuidv4(),
                rfqId: rfqIds.logisticsReroute,
                partId: partIds.logisticsLane,
                quantity: 2,
            },
        ]);

        await executor.insert(rfqSuppliers).values([
            {
                id: uuidv4(),
                rfqId: rfqIds.batteryPack,
                supplierId: supplierIds.pacific,
                status: "quoted",
                quoteAmount: decimal(1560000),
                aiAnalysis: "Competitive battery pack pricing with acceptable lead-time risk.",
                createdAt: dateFromNow(-8),
            },
            {
                id: uuidv4(),
                rfqId: rfqIds.batteryPack,
                supplierId: supplierIds.atlas,
                status: "quoted",
                quoteAmount: decimal(1495000),
                aiAnalysis: "Higher service confidence and stronger warranty structure.",
                createdAt: dateFromNow(-7),
            },
            {
                id: uuidv4(),
                rfqId: rfqIds.logisticsReroute,
                supplierId: supplierIds.redMesa,
                status: "quoted",
                quoteAmount: decimal(990000),
                aiAnalysis: "Requires compliance remediation before award.",
                createdAt: dateFromNow(-22),
            },
        ]);

        await executor.insert(sourcingEvents).values([
            {
                id: uuidv4(),
                rfqId: rfqIds.batteryPack,
                status: "evaluation",
                launchedAt: dateFromNow(-9, 9),
                bidDeadline: dateFromNow(6, 17),
                qaDeadline: dateFromNow(2, 17),
                evaluationDeadline: dateFromNow(8, 17),
                scoringModel: JSON.stringify({ price: 40, quality: 25, delivery: 20, risk: 15 }),
                scenarioComparison: JSON.stringify([
                    { supplier: "Atlas Components India", score: 91 },
                    { supplier: "Pacific Circuits Pte Ltd", score: 84 },
                ]),
                ownerId: primaryAdmin.id,
                createdAt: dateFromNow(-9),
                updatedAt: dateFromNow(-1),
            },
            {
                id: uuidv4(),
                rfqId: rfqIds.logisticsReroute,
                status: "awarded",
                launchedAt: dateFromNow(-24, 9),
                bidDeadline: dateFromNow(-18, 17),
                evaluationDeadline: dateFromNow(-16, 16),
                scoringModel: JSON.stringify({ price: 35, risk: 35, leadTime: 30 }),
                awardMemo: "Awarded with mitigation guardrails and weekly telemetry review.",
                awardedSupplierId: supplierIds.redMesa,
                awardedAt: dateFromNow(-15, 14),
                awardJustification: "Only bonded-lane capacity available inside required recovery window.",
                scenarioComparison: JSON.stringify([
                    { supplier: "Red Mesa Logistics LLC", score: 71 },
                ]),
                ownerId: internalUsers.operations,
                createdAt: dateFromNow(-24),
                updatedAt: dateFromNow(-15),
            },
        ]);

        await executor.insert(sourcingMessages).values([
            {
                id: uuidv4(),
                rfqId: rfqIds.batteryPack,
                supplierId: supplierIds.atlas,
                senderId: primaryAdmin.id,
                messageType: "clarification",
                subject: "Thermal telemetry scope",
                content: "Please confirm whether the quoted pack includes cell-level thermal telemetry.",
                isRead: "yes",
                createdAt: dateFromNow(-6, 11),
            },
            {
                id: uuidv4(),
                rfqId: rfqIds.batteryPack,
                supplierId: supplierIds.atlas,
                senderId: internalUsers.supplierPortal,
                messageType: "answer",
                subject: "Re: Thermal telemetry scope",
                content: "Yes, the quoted configuration includes the telemetry harness and calibration kit.",
                isRead: "yes",
                createdAt: dateFromNow(-6, 15),
            },
        ]);

        await executor.insert(procurementOrders).values([
            {
                id: orderIds.atlasMarch,
                supplierId: supplierIds.atlas,
                status: "fulfilled",
                totalAmount: decimal(1240000),
                contractId: contractIds.atlasFramework,
                requisitionId: requisitionIds.evProgram,
                incoterms: "DAP",
                asnNumber: "ASN-ATLAS-2403",
                carrier: "Blue Dart",
                trackingNumber: "BD-7729011",
                estimatedArrival: dateFromNow(-88),
                initialQuoteAmount: decimal(1365000),
                savingsAmount: decimal(125000),
                savingsType: "negotiated",
                createdAt: dateFromNow(-110),
            },
            {
                id: orderIds.nordforgeApril,
                supplierId: supplierIds.nordforge,
                status: "fulfilled",
                totalAmount: decimal(865000),
                contractId: contractIds.nordforgeSteel,
                requisitionId: requisitionIds.evProgram,
                incoterms: "FCA",
                asnNumber: "ASN-NF-2404",
                carrier: "DHL Freight",
                trackingNumber: "DHL-8821901",
                estimatedArrival: dateFromNow(-58),
                initialQuoteAmount: decimal(915000),
                savingsAmount: decimal(50000),
                savingsType: "volume_discount",
                createdAt: dateFromNow(-76),
            },
            {
                id: orderIds.pacificMay,
                supplierId: supplierIds.pacific,
                status: "sent",
                contractId: contractIds.pacificElectronics,
                requisitionId: requisitionIds.warehouseUpgrade,
                totalAmount: decimal(468000),
                incoterms: "CIP",
                asnNumber: "ASN-PC-2405",
                carrier: "FedEx",
                trackingNumber: "FDX-2201193",
                estimatedArrival: dateFromNow(6),
                initialQuoteAmount: decimal(515000),
                savingsAmount: decimal(47000),
                savingsType: "should_cost",
                createdAt: dateFromNow(-26),
            },
            {
                id: orderIds.desertJune,
                supplierId: supplierIds.desert,
                status: "approved",
                totalAmount: decimal(1390000),
                contractId: contractIds.atlasFramework,
                requisitionId: requisitionIds.evProgram,
                incoterms: "CFR",
                asnNumber: "ASN-DP-2406",
                carrier: "Maersk",
                trackingNumber: "MAE-3311900",
                estimatedArrival: dateFromNow(12),
                initialQuoteAmount: decimal(1495000),
                savingsAmount: decimal(105000),
                savingsType: "payment_term",
                createdAt: dateFromNow(-12),
            },
            {
                id: orderIds.redMesaJuly,
                supplierId: supplierIds.redMesa,
                status: "pending_approval",
                totalAmount: decimal(980000),
                contractId: contractIds.redMesaCarrier,
                requisitionId: requisitionIds.logisticsBuffer,
                incoterms: "FCA",
                asnNumber: "ASN-RM-2407",
                carrier: "Red Mesa",
                trackingNumber: "RM-4408181",
                estimatedArrival: dateFromNow(5),
                initialQuoteAmount: decimal(1030000),
                savingsAmount: decimal(50000),
                savingsType: "negotiated",
                createdAt: dateFromNow(-4),
            },
        ]);

        await executor.insert(orderItems).values([
            { id: uuidv4(), orderId: orderIds.atlasMarch, partId: partIds.microcontroller, quantity: 96, unitPrice: decimal(7900) },
            { id: uuidv4(), orderId: orderIds.atlasMarch, partId: partIds.copperHarness, quantity: 120, unitPrice: decimal(4000) },
            { id: uuidv4(), orderId: orderIds.nordforgeApril, partId: partIds.steelBracket, quantity: 310, unitPrice: decimal(1850) },
            { id: uuidv4(), orderId: orderIds.nordforgeApril, partId: partIds.servoMotor, quantity: 12, unitPrice: decimal(11250) },
            { id: uuidv4(), orderId: orderIds.pacificMay, partId: partIds.warehouseSensors, quantity: 80, unitPrice: decimal(3850) },
            { id: uuidv4(), orderId: orderIds.pacificMay, partId: partIds.servoMotor, quantity: 10, unitPrice: decimal(12500) },
            { id: uuidv4(), orderId: orderIds.desertJune, partId: partIds.resinPellets, quantity: 140, unitPrice: decimal(6900) },
            { id: uuidv4(), orderId: orderIds.desertJune, partId: partIds.copperHarness, quantity: 72, unitPrice: decimal(5900) },
            { id: uuidv4(), orderId: orderIds.redMesaJuly, partId: partIds.logisticsLane, quantity: 10, unitPrice: decimal(98000) },
        ]);

        await executor.insert(goodsReceipts).values([
            {
                id: receiptIds.atlas,
                orderId: orderIds.atlasMarch,
                receivedById: internalUsers.operations,
                receivedAt: dateFromNow(-102, 14),
                notes: "Inbound lot received with no shortages.",
                inspectionStatus: "passed",
                inspectionNotes: "Visual and quantity verification completed.",
            },
            {
                id: receiptIds.nordforge,
                orderId: orderIds.nordforgeApril,
                receivedById: internalUsers.operations,
                receivedAt: dateFromNow(-63, 15),
                notes: "Split delivery consolidated in warehouse.",
                inspectionStatus: "passed",
                inspectionNotes: "Minor packaging damage, no part impact.",
            },
            {
                id: receiptIds.desert,
                orderId: orderIds.desertJune,
                receivedById: internalUsers.operations,
                receivedAt: dateFromNow(-5, 12),
                notes: "Initial batch received for quarantine release.",
                inspectionStatus: "conditional",
                inspectionNotes: "Release after final SDS validation.",
            },
        ]);

        await executor.insert(qcInspections).values([
            {
                id: uuidv4(),
                receiptId: receiptIds.atlas,
                inspectorId: internalUsers.operations,
                status: "passed",
                visualInspectionPassed: "yes",
                quantityVerified: "yes",
                documentMatch: "yes",
                notes: "Pass. No deviations logged.",
                createdAt: dateFromNow(-102, 15),
            },
            {
                id: uuidv4(),
                receiptId: receiptIds.nordforge,
                inspectorId: internalUsers.operations,
                status: "passed",
                visualInspectionPassed: "yes",
                quantityVerified: "yes",
                documentMatch: "yes",
                notes: "Pass after repalletization.",
                createdAt: dateFromNow(-63, 16),
            },
            {
                id: uuidv4(),
                receiptId: receiptIds.desert,
                inspectorId: internalUsers.operations,
                status: "conditional",
                visualInspectionPassed: "yes",
                quantityVerified: "yes",
                documentMatch: "no",
                notes: "Awaiting updated safety data sheet.",
                createdAt: dateFromNow(-5, 13),
            },
        ]);

        await executor.insert(invoices).values([
            {
                id: invoiceIds.atlasPaid,
                orderId: orderIds.atlasMarch,
                supplierId: supplierIds.atlas,
                invoiceNumber: "INV-ATLAS-2403",
                amount: decimal(1240000),
                currency: "INR",
                region: "South Asia",
                country: "India",
                continent: "Asia",
                status: "paid",
                invoiceDate: dateFromNow(-106),
                dueDate: dateFromNow(-76),
                taxAmount: decimal(189153),
                subtotal: decimal(1050847),
                lineItems: JSON.stringify([
                    { description: "Vehicle Control MCU", quantity: 96, unitPrice: 7900, totalPrice: 758400 },
                    { description: "Copper Harness Assembly", quantity: 120, unitPrice: 4000, totalPrice: 480000 },
                ]),
                paymentTerms: "Net 30",
                purchaseOrderRef: orderIds.atlasMarch.slice(0, 8).toUpperCase(),
                documentUrl: "/demo/invoices/atlas-march.pdf",
                matchedAt: dateFromNow(-96),
                createdAt: dateFromNow(-106),
            },
            {
                id: invoiceIds.nordforgeMatched,
                orderId: orderIds.nordforgeApril,
                supplierId: supplierIds.nordforge,
                invoiceNumber: "NF-APR-8842",
                amount: decimal(865000),
                currency: "EUR",
                region: "Europe",
                country: "Germany",
                continent: "Europe",
                status: "matched",
                invoiceDate: dateFromNow(-66),
                dueDate: dateFromNow(-36),
                taxAmount: decimal(0),
                subtotal: decimal(865000),
                lineItems: JSON.stringify([
                    { description: "Chassis Support Bracket", quantity: 310, unitPrice: 1850, totalPrice: 573500 },
                    { description: "Warehouse Servo Motor", quantity: 12, unitPrice: 11250, totalPrice: 135000 },
                ]),
                paymentTerms: "2% 10 Net 30",
                purchaseOrderRef: orderIds.nordforgeApril.slice(0, 8).toUpperCase(),
                documentUrl: "/demo/invoices/nordforge-april.pdf",
                matchedAt: dateFromNow(-57),
                createdAt: dateFromNow(-66),
            },
            {
                id: invoiceIds.pacificPending,
                orderId: orderIds.pacificMay,
                supplierId: supplierIds.pacific,
                invoiceNumber: "PC-INV-5120",
                amount: decimal(468000),
                currency: "SGD",
                region: "Southeast Asia",
                country: "Singapore",
                continent: "Asia",
                status: "pending",
                invoiceDate: dateFromNow(-18),
                dueDate: dateFromNow(10),
                taxAmount: decimal(18720),
                subtotal: decimal(449280),
                lineItems: JSON.stringify([
                    { description: "Rack Health Sensor", quantity: 80, unitPrice: 3850, totalPrice: 308000 },
                    { description: "Warehouse Servo Motor", quantity: 10, unitPrice: 12500, totalPrice: 125000 },
                ]),
                paymentTerms: "Net 21",
                purchaseOrderRef: orderIds.pacificMay.slice(0, 8).toUpperCase(),
                documentUrl: "/demo/invoices/pacific-may.pdf",
                createdAt: dateFromNow(-18),
            },
            {
                id: invoiceIds.redMesaDisputed,
                orderId: orderIds.redMesaJuly,
                supplierId: supplierIds.redMesa,
                invoiceNumber: "RM-771-01",
                amount: decimal(1125000),
                currency: "USD",
                region: "North America",
                country: "United States",
                continent: "North America",
                status: "disputed",
                invoiceDate: dateFromNow(-2),
                dueDate: dateFromNow(14),
                taxAmount: decimal(0),
                subtotal: decimal(1125000),
                lineItems: JSON.stringify([
                    { description: "Dedicated Export Lane", quantity: 10, unitPrice: 112500, totalPrice: 1125000 },
                ]),
                paymentTerms: "Net 15",
                purchaseOrderRef: orderIds.redMesaJuly.slice(0, 8).toUpperCase(),
                documentUrl: "/demo/invoices/redmesa-july.pdf",
                createdAt: dateFromNow(-2),
            },
        ]);

        await executor.insert(documents).values([
            {
                id: uuidv4(),
                supplierId: supplierIds.atlas,
                contractId: contractIds.atlasFramework,
                name: "Atlas Framework Agreement.pdf",
                type: "contract",
                url: "/demo/contracts/atlas-framework.pdf",
                createdAt: dateFromNow(-118),
            },
            {
                id: uuidv4(),
                supplierId: supplierIds.atlas,
                orderId: orderIds.atlasMarch,
                name: "Atlas Invoice INV-ATLAS-2403.pdf",
                type: "invoice",
                url: "/demo/invoices/atlas-march.pdf",
                createdAt: dateFromNow(-106),
            },
            {
                id: uuidv4(),
                supplierId: supplierIds.pacific,
                rfqId: rfqIds.batteryPack,
                name: "Pacific Phase-2 Quote.xlsx",
                type: "quote",
                url: "/demo/rfqs/pacific-phase2-quote.xlsx",
                createdAt: dateFromNow(-8),
            },
        ]);

        await executor.insert(supplierPerformanceLogs).values([
            {
                id: uuidv4(),
                supplierId: supplierIds.atlas,
                recordedAt: dateFromNow(-20),
                deliveryRate: decimal(98),
                qualityScore: decimal(96),
                collaborationScore: 90,
                notes: "Excellent quarter close-out.",
            },
            {
                id: uuidv4(),
                supplierId: supplierIds.nordforge,
                recordedAt: dateFromNow(-25),
                deliveryRate: decimal(94),
                qualityScore: decimal(92),
                collaborationScore: 84,
                notes: "Pricing stable after annual lock.",
            },
            {
                id: uuidv4(),
                supplierId: supplierIds.redMesa,
                recordedAt: dateFromNow(-7),
                deliveryRate: decimal(78),
                qualityScore: decimal(81),
                collaborationScore: 52,
                notes: "Escalated after missed bonded transfer milestone.",
            },
        ]);

        await executor.insert(complianceObligations).values([
            {
                id: complianceIds.atlasIso,
                title: "Atlas ISO 27001 Renewal",
                description: "Renew information-security certificate before Q3 shipments.",
                supplierId: supplierIds.atlas,
                contractId: contractIds.atlasFramework,
                category: "certification",
                status: "expiring_soon",
                ownerId: primaryAdmin.id,
                documentRequired: "yes",
                expiresAt: dateFromNow(16),
                reminderDaysBefore: 30,
                lastReminderSentAt: dateFromNow(-3),
                escalationPolicy: JSON.stringify({ afterDays: 5, escalateTo: internalUsers.finance }),
                policyPack: "ISO_CONTROL",
                region: "South Asia",
                createdAt: dateFromNow(-30),
                updatedAt: dateFromNow(-3),
            },
            {
                id: complianceIds.nordforgeCyber,
                title: "NordForge Cyber Questionnaire",
                description: "Annual cyber risk attestation for fabrication tooling data exchange.",
                supplierId: supplierIds.nordforge,
                contractId: contractIds.nordforgeSteel,
                category: "cyber",
                status: "active",
                ownerId: primaryAdmin.id,
                documentRequired: "yes",
                documentUrl: "/demo/compliance/nordforge-cyber.pdf",
                evidenceSubmittedAt: dateFromNow(-12),
                expiresAt: dateFromNow(92),
                reminderDaysBefore: 45,
                escalationPolicy: JSON.stringify({ afterDays: 7, escalateTo: internalUsers.operations }),
                policyPack: "CYBER_TPRM",
                region: "Europe",
                createdAt: dateFromNow(-55),
                updatedAt: dateFromNow(-12),
            },
            {
                id: complianceIds.redMesaEsg,
                title: "Red Mesa ESG Corrective Action",
                description: "Submit modern slavery statement and emissions baseline.",
                supplierId: supplierIds.redMesa,
                contractId: contractIds.redMesaCarrier,
                category: "esg_attestation",
                status: "expired",
                ownerId: primaryAdmin.id,
                documentRequired: "yes",
                expiresAt: dateFromNow(-4),
                reminderDaysBefore: 20,
                escalationPolicy: JSON.stringify({ afterDays: 2, escalateTo: internalUsers.finance }),
                policyPack: "ESG_STANDARD",
                region: "North America",
                createdAt: dateFromNow(-28),
                updatedAt: dateFromNow(-4),
            },
        ]);

        await executor.insert(supplierRequests).values([
            {
                id: uuidv4(),
                supplierId: supplierIds.atlas,
                requestType: "compliance_attestation",
                title: "Submit ISO 27001 certificate copy",
                description: "Need the renewed certificate pack for the next governance review.",
                status: "sent",
                assigneeId: primaryAdmin.id,
                dueDate: dateFromNow(14),
                linkedObligationId: complianceIds.atlasIso,
                createdById: primaryAdmin.id,
                createdAt: dateFromNow(-4),
                updatedAt: dateFromNow(-4),
            },
            {
                id: uuidv4(),
                supplierId: supplierIds.redMesa,
                requestType: "corrective_action",
                title: "Provide emissions and labor remediation plan",
                description: "Executive review needs a signed remediation plan before lane award stays active.",
                status: "overdue",
                assigneeId: primaryAdmin.id,
                dueDate: dateFromNow(-2),
                linkedObligationId: complianceIds.redMesaEsg,
                createdById: primaryAdmin.id,
                createdAt: dateFromNow(-10),
                updatedAt: dateFromNow(-1),
            },
        ]);

        await executor.insert(supplierActionPlans).values([
            {
                id: uuidv4(),
                supplierId: supplierIds.redMesa,
                title: "Red Mesa service recovery",
                description: "Recover lane reliability and governance evidence before August board review.",
                severity: "critical",
                status: "in_progress",
                planType: "remediation",
                ownerId: primaryAdmin.id,
                dueDate: dateFromNow(18),
                steps: JSON.stringify([
                    { title: "Alternate lane validation", status: "completed" },
                    { title: "ESG evidence submission", status: "in_progress" },
                    { title: "Executive carrier checkpoint", status: "open" },
                ]),
                linkedEvidence: JSON.stringify([{ type: "ticket", url: "/admin/support" }]),
                createdById: primaryAdmin.id,
                createdAt: dateFromNow(-10),
                updatedAt: dateFromNow(-1),
            },
            {
                id: uuidv4(),
                supplierId: supplierIds.pacific,
                title: "Battery telemetry readiness",
                description: "Close remaining pilot readiness actions before phase-2 award.",
                severity: "medium",
                status: "active",
                planType: "development",
                ownerId: internalUsers.sourcing,
                dueDate: dateFromNow(22),
                steps: JSON.stringify([
                    { title: "Confirm telemetry harness BOM", status: "completed" },
                    { title: "Share pilot FAT video", status: "open" },
                ]),
                linkedEvidence: JSON.stringify([]),
                createdById: primaryAdmin.id,
                createdAt: dateFromNow(-8),
                updatedAt: dateFromNow(-2),
            },
        ]);

        await executor.insert(workflowTasks).values([
            {
                id: uuidv4(),
                title: "Review Atlas certificate before quarter close",
                description: "Compliance owner needs to validate the renewed ISO file and notify the steering committee.",
                entityType: "compliance_obligation",
                entityId: complianceIds.atlasIso,
                status: "open",
                priority: "high",
                assigneeId: primaryAdmin.id,
                createdById: primaryAdmin.id,
                dueDate: dateFromNow(8),
                slaDeadline: dateFromNow(10),
                nextAction: "Follow up with Atlas by 3 PM IST",
                createdAt: dateFromNow(-3),
                updatedAt: dateFromNow(-1),
            },
            {
                id: uuidv4(),
                title: "Resolve Red Mesa disputed invoice",
                description: "Invoice exceeds negotiated transport lane ceiling by 14.8%.",
                entityType: "invoice",
                entityId: invoiceIds.redMesaDisputed,
                status: "blocked",
                priority: "critical",
                assigneeId: primaryAdmin.id,
                createdById: internalUsers.finance,
                dueDate: dateFromNow(-1),
                slaDeadline: dateFromNow(1),
                nextAction: "Obtain corrected invoice before payment run",
                createdAt: dateFromNow(-2),
                updatedAt: dateFromNow(-1),
            },
            {
                id: uuidv4(),
                title: "Approve warehouse sensor requisition",
                description: "Budget check completed. Awaiting final sourcing approval.",
                entityType: "requisition",
                entityId: requisitionIds.warehouseUpgrade,
                status: "in_progress",
                priority: "medium",
                assigneeId: primaryAdmin.id,
                createdById: internalUsers.operations,
                dueDate: dateFromNow(3),
                slaDeadline: dateFromNow(5),
                nextAction: "Confirm spend is aligned to Q2 capex envelope",
                createdAt: dateFromNow(-6),
                updatedAt: dateFromNow(-1),
            },
            {
                id: uuidv4(),
                title: "Prepare battery RFQ award memo",
                description: "Top two bids are within 4.1%. Need final risk recommendation.",
                entityType: "rfq",
                entityId: rfqIds.batteryPack,
                status: "open",
                priority: "medium",
                assigneeId: internalUsers.sourcing,
                createdById: primaryAdmin.id,
                dueDate: dateFromNow(7),
                slaDeadline: dateFromNow(9),
                nextAction: "Complete supplier comparison note for CPO review",
                createdAt: dateFromNow(-2),
                updatedAt: dateFromNow(-1),
            },
        ]);

        await executor.insert(marketPriceIndex).values([
            {
                id: uuidv4(),
                partCategory: "Electronics",
                commodity: "Copper + MCU",
                benchmarkPrice: "8010.0000",
                source: "Internal blended benchmark",
                validFrom: dateFromNow(-30),
                validTo: dateFromNow(30),
                createdAt: dateFromNow(-30),
            },
            {
                id: uuidv4(),
                partCategory: "Steel",
                commodity: "Rolled Steel",
                benchmarkPrice: "1790.0000",
                source: "Metals desk",
                validFrom: dateFromNow(-30),
                validTo: dateFromNow(30),
                createdAt: dateFromNow(-30),
            },
            {
                id: uuidv4(),
                partCategory: "Logistics",
                commodity: "Bonded export lane",
                benchmarkPrice: "94000.0000",
                source: "Carrier benchmark",
                validFrom: dateFromNow(-20),
                validTo: dateFromNow(20),
                createdAt: dateFromNow(-20),
            },
            {
                id: uuidv4(),
                partCategory: "Chemicals",
                commodity: "PBT Resin",
                benchmarkPrice: "6760.0000",
                source: "Resin index",
                validFrom: dateFromNow(-15),
                validTo: dateFromNow(15),
                createdAt: dateFromNow(-15),
            },
        ]);

        await executor.insert(demandForecasts).values([
            {
                id: uuidv4(),
                partId: partIds.microcontroller,
                forecastDate: dateFromNow(30),
                predictedQuantity: 180,
                confidenceLower: 160,
                confidenceUpper: 205,
                trend: "up",
                seasonalityFactor: decimal(1.12),
                factors: JSON.stringify(["pilot expansion", "dealer launch readiness"]),
                createdAt: dateFromNow(-1),
            },
            {
                id: uuidv4(),
                partId: partIds.warehouseSensors,
                forecastDate: dateFromNow(45),
                predictedQuantity: 120,
                confidenceLower: 102,
                confidenceUpper: 138,
                trend: "stable",
                seasonalityFactor: decimal(1.03),
                factors: JSON.stringify(["warehouse retrofit", "planned rack automation"]),
                createdAt: dateFromNow(-1),
            },
        ]);

        await executor.insert(savingsRecords).values([
            {
                id: uuidv4(),
                entityType: "order",
                entityId: orderIds.atlasMarch,
                category: "negotiated",
                trackingStatus: "realized",
                forecastAmount: decimal(125000),
                realizedAmount: decimal(125000),
                baselineAmount: decimal(1365000),
                currency: "INR",
                notes: "Atlas framework lock beat the pilot quote baseline.",
                createdAt: dateFromNow(-100),
            },
            {
                id: uuidv4(),
                entityType: "order",
                entityId: orderIds.pacificMay,
                category: "should_cost",
                trackingStatus: "forecast",
                forecastAmount: decimal(47000),
                realizedAmount: decimal(0),
                baselineAmount: decimal(515000),
                currency: "SGD",
                notes: "Expected to realize savings after final invoice match.",
                createdAt: dateFromNow(-20),
            },
            {
                id: uuidv4(),
                entityType: "order",
                entityId: orderIds.redMesaJuly,
                category: "negotiated",
                trackingStatus: "disputed",
                forecastAmount: decimal(50000),
                realizedAmount: decimal(0),
                baselineAmount: decimal(1030000),
                currency: "USD",
                notes: "Disputed invoice is delaying savings validation.",
                createdAt: dateFromNow(-2),
            },
        ]);

        await executor.insert(paymentOptimizations).values([
            {
                id: uuidv4(),
                orderId: orderIds.nordforgeApril,
                invoiceId: invoiceIds.nordforgeMatched,
                supplierName: "NordForge Precision GmbH",
                invoiceAmount: decimal(865000),
                discountTerms: "2% 10 Net 30",
                currentDueDate: dateFromNow(-36),
                suggestedPaymentDate: dateFromNow(-45),
                potentialSavings: decimal(17300),
                savingsType: "early_payment_discount",
                reason: "Pay nine days earlier to capture supplier early settlement discount.",
                annualizedReturn: decimal(24.5),
                status: "recommended",
                createdAt: dateFromNow(-55),
            },
            {
                id: uuidv4(),
                orderId: orderIds.pacificMay,
                invoiceId: invoiceIds.pacificPending,
                supplierName: "Pacific Circuits Pte Ltd",
                invoiceAmount: decimal(468000),
                discountTerms: "Net 21",
                currentDueDate: dateFromNow(10),
                suggestedPaymentDate: dateFromNow(8),
                potentialSavings: decimal(7500),
                savingsType: "cashflow_alignment",
                reason: "Schedule settlement after inbound inspection clears to protect working capital.",
                annualizedReturn: decimal(11.0),
                status: "pending",
                createdAt: dateFromNow(-8),
            },
        ]);

        await executor.insert(fraudAlerts).values([
            {
                id: uuidv4(),
                entityType: "invoice",
                entityId: invoiceIds.redMesaDisputed,
                alertType: "unusual_amount",
                severity: "high",
                description: "Red Mesa invoice exceeds negotiated logistics lane value by 14.8%.",
                indicators: JSON.stringify([
                    "Invoice value materially above PO ceiling",
                    "Supplier currently on remediation plan",
                    "Pending approval order with disputed invoice",
                ]),
                suggestedAction: "Hold payment and request supplier credit note before approval.",
                falsePositiveProbability: decimal(14),
                status: "open",
                createdAt: dateFromNow(-2),
            },
            {
                id: uuidv4(),
                entityType: "supplier",
                entityId: supplierIds.redMesa,
                alertType: "new_vendor_high_value",
                severity: "critical",
                description: "Recently onboarded carrier accumulated near-seven-figure routed capacity within 45 days.",
                indicators: JSON.stringify([
                    "Supplier age under 60 days",
                    "Large routed value concentration",
                    "ESG evidence overdue",
                ]),
                suggestedAction: "Escalate to finance and sourcing leadership before further lane awards.",
                falsePositiveProbability: decimal(8),
                status: "open",
                createdAt: dateFromNow(-4),
            },
        ]);

        await executor.insert(agentExecutions).values([
            {
                id: uuidv4(),
                agentName: "fraud-detection",
                status: "success",
                inputContext: JSON.stringify({ lookbackDays: 30 }),
                outputData: JSON.stringify({ alerts: 2 }),
                confidenceScore: 91,
                tokenUsage: 8421,
                executionTimeMs: 4210,
                triggeredBy: "scheduled",
                userId: primaryAdmin.id,
                createdAt: dateFromNow(-2),
                completedAt: dateFromNow(-2, 10, 7),
            },
            {
                id: uuidv4(),
                agentName: "payment-optimizer",
                status: "success",
                inputContext: JSON.stringify({ openInvoices: 2 }),
                outputData: JSON.stringify({ recommendations: 2 }),
                confidenceScore: 88,
                tokenUsage: 6124,
                executionTimeMs: 3160,
                triggeredBy: "manual",
                userId: primaryAdmin.id,
                createdAt: dateFromNow(-1),
                completedAt: dateFromNow(-1, 12, 5),
            },
        ]);

        await executor.insert(agentRecommendations).values([
            {
                id: uuidv4(),
                agentName: "payment-optimizer",
                recommendationType: "early_payment",
                title: "Capture NordForge early payment discount",
                description: "Move settlement forward by nine days to unlock a 2% discount on the matched invoice.",
                impact: "high",
                estimatedSavings: decimal(17300),
                status: "pending",
                confidence: 89,
                ownerId: primaryAdmin.id,
                businessImpact: "Improves working capital yield while strengthening preferred supplier status.",
                explanation: "Matched invoice and payment terms make this a low-risk discount capture.",
                executionPayload: JSON.stringify({ invoiceId: invoiceIds.nordforgeMatched }),
                entityType: "invoice",
                entityId: invoiceIds.nordforgeMatched,
                dueDate: dateFromNow(2),
                createdAt: dateFromNow(-1),
                expiresAt: dateFromNow(5),
            },
            {
                id: uuidv4(),
                agentName: "predictive-bottleneck",
                recommendationType: "workflow_recovery",
                title: "Escalate Red Mesa invoice resolution",
                description: "Finance and sourcing should jointly resolve the disputed lane invoice before the next payout cycle.",
                impact: "critical",
                estimatedSavings: decimal(50000),
                status: "approved",
                confidence: 93,
                ownerId: primaryAdmin.id,
                businessImpact: "Prevents leakage against contracted rates and short-term cashflow distortion.",
                explanation: "Dispute is already blocking downstream approval and telemetry shows rising cycle time.",
                executionPayload: JSON.stringify({ task: "joint_escalation" }),
                entityType: "invoice",
                entityId: invoiceIds.redMesaDisputed,
                dueDate: dateFromNow(1),
                reviewedBy: primaryAdmin.id,
                reviewedAt: dateFromNow(-1),
                createdAt: dateFromNow(-2),
                expiresAt: dateFromNow(4),
            },
        ]);

        await executor.insert(systemTelemetry).values([
            {
                id: uuidv4(),
                type: "metric",
                scope: "AxiomCopilot",
                key: "response_latency_ms",
                value: "1620.0000",
                metadata: JSON.stringify({ mode: "fallback-ready" }),
                userId: primaryAdmin.id,
                createdAt: dateFromNow(-1),
            },
            {
                id: uuidv4(),
                type: "metric",
                scope: "FraudDetectionAgent",
                key: "execution_latency_ms",
                value: "4210.0000",
                metadata: JSON.stringify({ alertsGenerated: 2 }),
                userId: primaryAdmin.id,
                createdAt: dateFromNow(-2),
            },
            {
                id: uuidv4(),
                type: "error",
                scope: "InvoiceOCR",
                key: "fallback_activation",
                value: "1.0000",
                metadata: JSON.stringify({ reason: "low_confidence_parse" }),
                userId: primaryAdmin.id,
                createdAt: dateFromNow(-1),
            },
        ]);

        await executor.insert(auditLogs).values([
            {
                id: uuidv4(),
                userId: primaryAdmin.id,
                action: "CREATE",
                entityType: "order",
                entityId: orderIds.atlasMarch,
                details: "Created Atlas March fulfillment order.",
                createdAt: dateFromNow(-110),
            },
            {
                id: uuidv4(),
                userId: primaryAdmin.id,
                action: "APPROVE",
                entityType: "order",
                entityId: orderIds.atlasMarch,
                details: "Approved Atlas March order after commercial review.",
                createdAt: dateFromNow(-109),
            },
            {
                id: uuidv4(),
                userId: internalUsers.finance,
                action: "CREATE",
                entityType: "invoice",
                entityId: invoiceIds.redMesaDisputed,
                details: "Captured Red Mesa logistics invoice from supplier upload.",
                createdAt: dateFromNow(-2),
            },
            {
                id: uuidv4(),
                userId: primaryAdmin.id,
                action: "UPDATE",
                entityType: "invoice",
                entityId: invoiceIds.redMesaDisputed,
                details: "Marked invoice disputed because value exceeded approved lane ceiling.",
                createdAt: dateFromNow(-1),
            },
        ]);

        await executor.insert(notifications).values([
            {
                id: uuidv4(),
                userId: primaryAdmin.id,
                title: "Compliance Deadline Approaching",
                message: "Atlas ISO 27001 renewal expires in 16 days.",
                type: "warning",
                isRead: "no",
                link: "/admin/compliance",
                createdAt: dateFromNow(-1),
            },
            {
                id: uuidv4(),
                userId: primaryAdmin.id,
                title: "Invoice Disputed",
                message: "Red Mesa invoice RM-771-01 has been moved to dispute review.",
                type: "error",
                isRead: "no",
                link: "/admin/financial-matching",
                createdAt: dateFromNow(-1),
            },
            {
                id: uuidv4(),
                userId: internalUsers.sourcing,
                title: "RFQ Evaluation Ready",
                message: "Battery Pack Phase-2 now has two competitive bids for award analysis.",
                type: "success",
                isRead: "no",
                link: "/sourcing/rfqs",
                createdAt: dateFromNow(-1),
            },
        ]);

        await executor.insert(comments).values([
            {
                id: uuidv4(),
                userId: primaryAdmin.id,
                entityType: "supplier",
                entityId: supplierIds.redMesa,
                text: "Keep this supplier in the workshop because it demonstrates risk, compliance, and dispute flows in one place.",
                createdAt: dateFromNow(-1),
            },
        ]);

        await executor.insert(supportTickets).values([
            {
                id: uuidv4(),
                ticketNumber: "PMA-2026-04-001",
                submittedById: internalUsers.operations,
                subject: "Need approval for alternate logistics lane",
                description: "The recovery lane for North America is ready, but we need finance approval before the next outbound wave.",
                category: "logistics",
                priority: "high",
                status: "in_progress",
                createdAt: dateFromNow(-5),
            },
            {
                id: uuidv4(),
                ticketNumber: "PMA-2026-04-002",
                submittedById: internalUsers.finance,
                subject: "Disputed carrier invoice needs sourcing context",
                description: "Finance needs the approved rate card and emergency addendum before releasing or rejecting the invoice.",
                category: "invoice",
                priority: "critical",
                status: "open",
                createdAt: dateFromNow(-2),
            },
            {
                id: uuidv4(),
                ticketNumber: "PMA-2026-04-003",
                submittedById: internalUsers.supplierPortal,
                subject: "Supplier portal access for telemetry attachment",
                description: "Atlas account team wants to upload an updated certificate bundle and telemetry annex.",
                category: "supplier_portal",
                priority: "medium",
                status: "resolved",
                resolution: "Portal permission pack refreshed and user notified.",
                resolvedAt: dateFromNow(-1),
                createdAt: dateFromNow(-6),
            },
        ]);

        await executor.insert(matchingTolerances).values([
            {
                id: uuidv4(),
                name: "Global Electronics Match Rule",
                description: "Default tolerance for electronics and automation invoices.",
                category: "Electronics",
                priceTolerancePercent: decimal(2),
                quantityTolerancePercent: decimal(5),
                allowPartialDelivery: "yes",
                exceptionReasons: JSON.stringify(["freight_included", "approved price refresh"]),
                isActive: "yes",
                createdAt: dateFromNow(-40),
            },
        ]);

        await executor.insert(approvalPolicies).values([
            {
                id: uuidv4(),
                name: "High Value Logistics Approval",
                description: "Route large logistics commitments to finance plus admin review.",
                entityType: "order",
                policyType: "amount",
                conditions: JSON.stringify({ minAmount: 900000, category: "Logistics" }),
                approverIds: [primaryAdmin.id, internalUsers.finance],
                approverRole: "admin",
                escalationTimeoutHours: 24,
                isActive: "yes",
                priority: 20,
                createdAt: dateFromNow(-50),
                updatedAt: dateFromNow(-10),
            },
        ]);

        await executor.insert(importJobs).values([
            {
                id: uuidv4(),
                entityType: "orders",
                status: "completed",
                fileName: "axiom-demo-orders-apr-2026.csv",
                totalRows: 128,
                successRows: 128,
                errorRows: 0,
                validationReport: JSON.stringify([]),
                fieldMapping: JSON.stringify({ Supplier: "supplierId", Total: "totalAmount" }),
                sourceSystemId: "SAP-QA",
                rollbackData: JSON.stringify({ insertedOrders: 5 }),
                importedById: primaryAdmin.id,
                startedAt: dateFromNow(-9),
                completedAt: dateFromNow(-9, 10, 12),
                createdAt: dateFromNow(-9),
            },
        ]);

        return {
            counts: {
                admins: preservedAdmins.length,
                users: preservedAdmins.length + 4,
                suppliers: 5,
                parts: 8,
                contracts: 4,
                rfqs: 2,
                orders: 5,
                invoices: 4,
                tasks: 4,
                complianceObligations: 3,
                fraudAlerts: 2,
                supportTickets: 3,
            },
        };
    });
}
